version: '2'

services:
    db:
        image: mysql:5.7.20
        volumes:
            - "./.data/db:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    php:
        build:
            context: php-fpm
            args:
                TIMEZONE: ${TIMEZONE}
        volumes:
            - ${SYMFONY_APP_PATH}:/var/www/symfony
            - ./logs/symfony:/var/www/symfony/var/log
    nginx:
        build: nginx
        ports:
            - ${NGINX_PORT}:80
        volumes_from:
            - php
        volumes:
            - ./logs/nginx/:/var/log/nginx
    redis:
        image: redis:4.0.10
        volumes:
            - ../data/redis:/data
        restart: always

#TODO: adjust permissions
    node:
        image: node:8.15.0
        ports:
            - 5000:3000
        volumes:
            - ./node:/var/www/node
        working_dir: /var/www/node
        command: yarn start
