security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    providers:
        db_user_provider:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^(?!/register)
            http_basic: ~
            provider: db_user_provider
